### ISSUE TITLE
Free Arrow in the term of Monadic Stream Function

### ISSUE THREAD

**Issue by Rizary** [coot/free-category#27]
Hi,

I am sending you a message on twitter, but I will post it anyway. So, I just watched your video on Haskell exchange. Too bad it has to end before you can show the example. I have a similar idea about free or freer arrow (though I am still at the beginner level).  For the first time, I have a look into funflow's Arrow Free module.

Moreover, I like the idea of Monadic Stream Function here in 

`data MSF m a b = MSF { unMSF :: a -> m (b, MSF m a b) }` 

([further reference](http://hackage.haskell.org/package/dunai-0.5.1)). 

So, looking at the CPS style of `A f a b`, 

```
newtype A f a b
  = A { runA :: forall r. Arrow r
             => (forall x y. f x y -> r x y)
             -> r a b
      }
```

is it the same result with different approach?

May I know about how you build your program with only Free Arrow? I saw that you put instance `FreeAlgebra2` on the Arrow. Is it possible without the `FreeAlgebra2`?

**Comment by coot** [comment]
This seems unrelated to the library.

**Comment by coot** [comment]
I don't see how `MSF` is related to `A` (which is a higher order function).

> May I know about how you build your program with only Free Arrow? I saw that you put instance FreeAlgebra2 on the Arrow. Is it possible without the FreeAlgebra2?
which program?
Likely so, but the interpretation will be limited to only pure monads. `Arrow` allows to embed pure arrows, rather than Kleisli arrows (see `EffCat`).

**Comment by Rizary** [comment]
@coot I think I misread regarding this [line]( https://github.com/coot/free-category/blob/master/examples/src/LoginStateMachine.hs#L17), which is commented now.

**Comment by Rizary** [comment]
Regarding MSF, it is noted (I realize it couple weeks ago).

**Comment by coot** [comment]
> @coot I think I misread regarding this line, which is commented now.

For that line: one could re-write the module using `FreeAlgebra2` constraint, but I didn't bother to do so.  It would make it harder to get the main point of this example (simplicity matters!)

**Comment by Rizary** [comment]
cool !! I'll take a look at this repo further (I'm starting to learn Arrow, and found this repo). Thank you for your explanation.
