### ISSUE TITLE
Document how to use shell.nix

### ISSUE THREAD

**Issue by turion** [coot/free-category#29]
Thanks a lot for this project! It's very useful for an experiment I want to make.

I was pleasantly surprised to see a `shell.nix`, but it's unclear to me how to use it:

```
$ nix-shell
error: getting status of '/home/turion/haskell/free-category/nix/nixpkgs.nix': No such file or directory
```

**Comment by turion** [comment]
I guess the shell.nix actually doesn't work and wasn't updated when switching to IOHK

**Comment by coot** [comment]
Yes, I should remove it.

**Comment by coot** [comment]
Removed in 29bcbf6
