### ISSUE TITLE
Free arrows are not inspectable?

### ISSUE THREAD

**Issue by gardspirito** [coot/free-category#42]
I'm new to free arrows so it's likely for me not to understand something, but why internal representation of Arr is not exposed? I'm talking about `Cons` constructor which remains non-exported.

My use case involves rebuilding the arrow before execution by simplifying and dropping some steps.

**Comment by coot** [comment]
It can be exposed, I am not sure if there's any reason against it.

**Comment by gardspirito** [comment]
Well, it can (and I see no reasons why not), but I'm not sure that it solves my problem specifically, so I believe that you know better whether it should or should not be exposed.

Sorry for opening the issue.

**Comment by coot** [comment]
#43
